scene.onOverlapTile(SpriteKind.Player, myTiles.transparency16, function (sprite, location) {
	
})
statusbars.onZero(StatusBarKind.Health, function (status) {
	
})
let Player_1 = sprites.create(img`
    ...................
    ...................
    .......fffff.......
    ......ffdddff......
    ......fd2d2df......
    .......ddddd.......
    .......ddedd.......
    ........ddd........
    ......deddeee......
    ......eeeeede......
    ......deeeedd......
    ......ddeeeed......
    ......feedeef......
    .......ee.ee.......
    .......ed.ee.......
    .......ee.de.......
    .......ff.ff.......
    ...................
    ...................
    `, SpriteKind.Player)
controller.moveSprite(Player_1)
scene.cameraFollowSprite(Player_1)
tiles.placeOnRandomTile(Player_1, myTiles.transparency16)
let health = statusbars.create(20, 4, StatusBarKind.Health)
health.setColor(2, 15, 0)
health.setStatusBarFlag(StatusBarFlag.SmoothTransition, true)
health.attachToSprite(Player_1, 0, 0)
